server:
  port: 8989
logging:
  level:
    web: DEBUG
spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      default-filters: TokenRelay
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
      routes:
        - id: USER-SERVICE
          uri: http://localhost:5050/
          predicates:
            - Path=/users/**
        - id: AGENCE-SERVICE
          uri: http://localhost:5051/
          predicates:
            - Path=/agence/**
        - id: CAMION-SERVICE
          uri: http://localhost:5052/
          predicates:
            - Path=/camion/**
        - id: CONTRAT-SERVICE
          uri: http://localhost:5053/
          predicates:
            - Path=/contrat/**
        - id: FACTURE-SERVICE
          uri: http://localhost:5054/
          predicates:
            - Path=/facture/**
        - id: RECU-SERVICE
          uri: http://localhost:5055/
          predicates:
            - Path=/recu/**
        - id: SERVICE-SERVICE
          uri: http://localhost:5056/
          predicates:
            - Path=/service/**
        - id: VEHICULE-SERVICE
          uri: http://localhost:5057/
          predicates:
            - Path=/vehicule/**
        - id: PARKING-SERVICE
          uri: http://localhost:5058/
          predicates:
              - Path=/parking/**
        - id: SOCIETE-REMORQUAGE-SERVICE
          uri: http://localhost:5059/
          predicates:
            - Path=/societeRemorquage/**
        - id: ASSURANCE-SERVICE
          uri: http://localhost:5060/
          predicates:
            - Path=/assurance/**
        - id: GARAGE-SERVICE
          uri: http://localhost:5061/
          predicates:
            - Path=/garage/**
        - id: ORDRE-SERVICE
          uri: http://localhost:5062/
          predicates:
            - Path=/ordre/**

############# EUREKA ##############
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/