# Enable these to debug the Authorization flow
logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG
server:
  port: 8989

management:
  endpoints:
    web:
      exposure:
        include: "*"


spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: USER-SERVICE
          uri: http://localhost:9090
          predicates:
            - Path=/Users/**
        - id: PARKING-SERVICE
          uri: http://localhost:9191
          predicates:
            - Path=/parking/**
