package com.tunidesign.vehiculemicroservice.model.ennumeration;

public enum Marque {
    ABARTH, ALFA ,ROMEO ,ALPINE ,ASTON ,MARTIN ,AUDI, BENTLEY ,BMW ,BOLLORE ,BRP ,BUGATTI ,CADILLAC ,CATERHAM ,
    CHEVROLET ,CHRYSLER ,CITROËN ,CUPRA ,DACIA ,DAIHATSU ,DEVINCI ,DODGE ,DS ,FERRARI ,FIAT ,FISKER ,FORD ,G, M ,C, GORDON,
    MURRAY ,AUTOMOTIVE ,HONDA ,HUMMER ,HYUNDAI ,INFINITI, ISUZU, JAGUAR, JANNARELLY ,JEEP ,KIA, KOENIGSEGG ,KTM ,SPORTCAR,
    LAMBORGHINI ,LANCIA, LAND_ROVER ,LEXUS ,LOTUS ,MASERATI ,MAYBACH ,MAZDA ,MCLAREN ,MERCEDES ,MG ,MOTOR ,MINI ,MITSUBISHI ,
    NISSAN ,OPEL ,PAGANI, PEUGEOT ,PGO ,POLESTAR ,PORSCHE, RENAULT, RIMAC ,RIVIAN, ROLLS ,ROYCE ,SAAB, SEAT, SERES, SHELBY,
    SKODA ,SMART ,SSANGYONG ,SUBARU, SUZUKI ,TESLA ,TOYOTA, VENTURI ,VOLKSWAGEN ,VOLVO, ZENVO,CLASSE_C,
    COROLLA,DUSTER, A1, C4, X3 , YARIS,SÉRIE_1 ,A3 ,CLASSE_A ,CLIO ,GOLF ,SANDERO, CAPTUR , TUCSON ,TWINGO ,GLC,
    X1, MÉGANE ,C3, C_HR  ,POLO ,MODEL_3 ,T_ROC ,_T_CROSS_, ARKANA ,C3_AIRCROSS ,PUMA, YARIS_CROSS ,SPRING
}
