package com.tunidesign.utilisateurmicroservice.model.enumeration;

public enum Role {
	CLIENT, SUPER_ADMIN, SOCIETE_REMORQUAGE_ADMIN, TA, DRIVER, AGENCY_ADMIN, INSURANCE_ADMIN,
	EXPERT, AGENCE_LOCATION_ADMIN, GARAGISTE_ADMIN, LAVAGISTE_ADMIN
}